/*
 * Copyright (c) 2015 Cossack Labs Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef ECRYPT_SECURE_CELL_ALG_H
#define ECRYPT_SECURE_CELL_ALG_H

#include <ecconnect/ecconnect_sym.h>

#ifndef ECRYPT_DEFAULT_PBKDF2_ITERATIONS
#define ECRYPT_DEFAULT_PBKDF2_ITERATIONS 314110
#endif

#ifdef ECRYPT_AUTH_SYM_ALG_AES_256_GCM
#define ECRYPT_AUTH_SYM_KEY_LENGTH ECCONNECT_SYM_256_KEY_LENGTH
#define ECRYPT_AUTH_SYM_ALG (ECCONNECT_SYM_AES_GCM | ECRYPT_AUTH_SYM_KEY_LENGTH)
#define ECRYPT_AUTH_SYM_IV_LENGTH 12
#define ECRYPT_AUTH_SYM_AUTH_TAG_LENGTH 16
#define ECRYPT_AUTH_SYM_PASSPHRASE_ALG (ECRYPT_AUTH_SYM_ALG | ECCONNECT_SYM_PBKDF2)
#define ECRYPT_AUTH_SYM_PBKDF2_SALT_LENGTH 16
#define ECRYPT_AUTH_SYM_PBKDF2_ITERATIONS (ECRYPT_DEFAULT_PBKDF2_ITERATIONS)
#endif

#ifdef ECRYPT_AUTH_SYM_ALG_AES_128_GCM
#define ECRYPT_AUTH_SYM_KEY_LENGTH ECCONNECT_SYM_128_KEY_LENGTH
#define ECRYPT_AUTH_SYM_ALG (ECCONNECT_SYM_AES_GCM | ECRYPT_AUTH_SYM_KEY_LENGTH)
#define ECRYPT_AUTH_SYM_IV_LENGTH 12
#define ECRYPT_AUTH_SYM_AUTH_TAG_LENGTH 16
#define ECRYPT_AUTH_SYM_PASSPHRASE_ALG (ECRYPT_AUTH_SYM_ALG | ECCONNECT_SYM_PBKDF2)
#define ECRYPT_AUTH_SYM_PBKDF2_SALT_LENGTH 16
#define ECRYPT_AUTH_SYM_PBKDF2_ITERATIONS (ECRYPT_DEFAULT_PBKDF2_ITERATIONS)
#endif

#ifdef ECRYPT_AUTH_SYM_ALG_AES_192_GCM
#define ECRYPT_AUTH_SYM_KEY_LENGTH ECCONNECT_SYM_192_KEY_LENGTH
#define ECRYPT_AUTH_SYM_ALG (ECCONNECT_SYM_AES_GCM | ECRYPT_AUTH_SYM_KEY_LENGTH)
#define ECRYPT_AUTH_SYM_IV_LENGTH 12
#define ECRYPT_AUTH_SYM_AUTH_TAG_LENGTH 16
#define ECRYPT_AUTH_SYM_PASSPHRASE_ALG (ECRYPT_AUTH_SYM_ALG | ECCONNECT_SYM_PBKDF2)
#define ECRYPT_AUTH_SYM_PBKDF2_SALT_LENGTH 16
#define ECRYPT_AUTH_SYM_PBKDF2_ITERATIONS (ECRYPT_DEFAULT_PBKDF2_ITERATIONS)
#endif

/*default values*/
#ifndef ECRYPT_AUTH_SYM_ALG
#define ECRYPT_AUTH_SYM_KEY_LENGTH ECCONNECT_SYM_256_KEY_LENGTH
#define ECRYPT_AUTH_SYM_ALG (ECCONNECT_SYM_AES_GCM | ECRYPT_AUTH_SYM_KEY_LENGTH)
#define ECRYPT_AUTH_SYM_IV_LENGTH 12
#define ECRYPT_AUTH_SYM_AUTH_TAG_LENGTH 16
#define ECRYPT_AUTH_SYM_PASSPHRASE_ALG (ECRYPT_AUTH_SYM_ALG | ECCONNECT_SYM_PBKDF2)
#define ECRYPT_AUTH_SYM_PBKDF2_SALT_LENGTH 16
#define ECRYPT_AUTH_SYM_PBKDF2_ITERATIONS (ECRYPT_DEFAULT_PBKDF2_ITERATIONS)
#endif

#define ECRYPT_AUTH_SYM_MAX_KEY_LENGTH ECCONNECT_SYM_256_KEY_LENGTH

#ifdef ECRYPT_SYM_ALG_AES_256_CTR
#define ECRYPT_SYM_KEY_LENGTH ECCONNECT_SYM_256_KEY_LENGTH
#define ECRYPT_SYM_ALG (ECCONNECT_SYM_AES_CTR | ECRYPT_SYM_KEY_LENGTH)
#define ECRYPT_SYM_IV_LENGTH 16
#endif

#ifdef ECRYPT_SYM_ALG_AES_192_CTR
#define ECRYPT_SYM_KEY_LENGTH ECCONNECT_SYM_192_KEY_LENGTH
#define ECRYPT_SYM_ALG (ECCONNECT_SYM_AES_CTR | ECRYPT_SYM_KEY_LENGTH)
#define ECRYPT_SYM_IV_LENGTH 16
#endif

#ifdef ECRYPT_SYM_ALG_AES_128_CTR
#define ECRYPT_SYM_KEY_LENGTH ECCONNECT_SYM_128_KEY_LENGTH
#define ECRYPT_SYM_ALG (ECCONNECT_SYM_AES_CTR | ECRYPT_SYM_KEY_LENGTH)
#define ECRYPT_SYM_IV_LENGTH 16
#endif

/*default values*/
#ifndef ECRYPT_SYM_ALG

#define ECRYPT_SYM_KEY_LENGTH ECCONNECT_SYM_256_KEY_LENGTH
#define ECRYPT_SYM_ALG (ECCONNECT_SYM_AES_CTR | ECRYPT_SYM_KEY_LENGTH)
#define ECRYPT_SYM_IV_LENGTH 16
#endif

static inline bool ecconnect_alg_reserved_bits_valid(uint32_t alg)
{
    static const uint32_t used_bits = ECCONNECT_SYM_KEY_LENGTH_MASK | ECCONNECT_SYM_PADDING_MASK
                                      | ECCONNECT_SYM_KDF_MASK | ECCONNECT_SYM_ALG_MASK;
    return (alg & ~used_bits) == 0;
}

static inline size_t ecconnect_alg_key_length(uint32_t alg)
{
    return (alg & ECCONNECT_SYM_KEY_LENGTH_MASK) / 8;
}

static inline uint32_t ecconnect_alg_kdf(uint32_t alg)
{
    return alg & ECCONNECT_SYM_KDF_MASK;
}

#endif /* ECRYPT_SECURE_CELL_ALG_H */
